"""Builder for ConflictQA-PopQA (Xie et al. 2023, Adaptive Chameleon).

Each raw row has a PopQA question + native Wikidata GT aliases, plus two
LLM-generated evidence passages (both generated by the *source* LLM named in
the filename):
  parametric_memory_aligned_evidence → supports the source LLM's memory answer
  counter_memory_aligned_evidence    → supports a counterfactual answer

For each raw row we emit 2 DatasetRows (one per evidence), with the label
determined by whether the corresponding short answer alias-matches GT:
  row-param:   ck_relation = sup if alias_match(memory_answer, gt)   else conf
  row-counter: ck_relation = sup if alias_match(counter_answer, gt)  else conf

GT origin:          "wikidata+aliases" (PopQA's native aliases)
ck_text origin:     "llm_synth_model_specific" (tagged with source_model)
ck_relation_source: "alias_match"

source_model is tagged per-file (e.g. "llama2-7b", "llama2-70b", "chatgpt", "gpt4").
"""
from __future__ import annotations

import json
from collections.abc import Iterator
from pathlib import Path

from saber.config import DATA_ROOT
from saber.data.alias_match import alias_match
from saber.data.schema import DatasetRow

RAW_DIR = DATA_ROOT / "raw" / "conflictqa"


def _iter_jsonl_or_json(path: Path):
    """ConflictQA is typically a single JSON list; fall back to JSONL detection."""
    text = path.read_text()
    try:
        data = json.loads(text)
        if isinstance(data, list):
            yield from data
            return
    except json.JSONDecodeError:
        pass
    # JSONL fallback
    for line in text.splitlines():
        line = line.strip()
        if line:
            yield json.loads(line)


def _build_one(source_model: str) -> list[DatasetRow]:
    """source_model ∈ {'llama2-7b', 'llama2-70b', 'chatgpt', 'gpt4'}."""
    path = RAW_DIR / f"conflictQA-popQA-{source_model}.json"
    dataset_name = f"conflictqa-popqa-{source_model}"
    rows: list[DatasetRow] = []

    for i, r in enumerate(_iter_jsonl_or_json(path)):
        question = r.get("question")
        gt_raw = r.get("ground_truth")
        if isinstance(gt_raw, str):
            gt_raw = [gt_raw]
        memory_answer = r.get("memory_answer")
        counter_answer = r.get("counter_answer")
        param_ev = r.get("parametric_memory_aligned_evidence")
        counter_ev = r.get("counter_memory_aligned_evidence")
        if not (question and gt_raw and memory_answer and counter_answer and param_ev and counter_ev):
            continue

        gt_list = [str(v).strip() for v in gt_raw if v]
        if not gt_list:
            continue
        gt_text = gt_list[0]

        # Alias-match each short answer against GT aliases → determine ck_relation
        mem_is_gt = alias_match(str(memory_answer), gt_list)
        ctr_is_gt = alias_match(str(counter_answer), gt_list)

        common_meta = {
            "popularity": r.get("popularity"),
            "subject_desc": r.get("subj"),
            "property": r.get("property"),
        }

        # Row 1 — passage = param_ev (supports memory_answer)
        rel1 = "supportive" if mem_is_gt else "conflicting"
        rows.append(DatasetRow(
            qid=f"{dataset_name}-{i:06d}-param",
            dataset=dataset_name,
            dataset_family="conflictqa",
            raw_idx=i,
            raw_split=None,
            question=question,
            question_format="open",
            options=None,
            ground_truth=gt_list,
            ground_truth_text=gt_text,
            ground_truth_origin="wikidata+aliases",
            ck_text=param_ev,
            ck_text_origin="llm_synth_model_specific",
            ck_target_answer=str(memory_answer).strip(),
            ck_target_matches_gt=mem_is_gt,
            ck_relation=rel1,
            ck_relation_is_core=True,
            ck_relation_source="alias_match",
            ck_sub_type=None,
            hop_count=1,
            source_model=source_model,
            metadata={**common_meta, "ck_source_field": "parametric_memory_aligned_evidence"},
        ))

        # Row 2 — passage = counter_ev (supports counter_answer)
        rel2 = "supportive" if ctr_is_gt else "conflicting"
        rows.append(DatasetRow(
            qid=f"{dataset_name}-{i:06d}-counter",
            dataset=dataset_name,
            dataset_family="conflictqa",
            raw_idx=i,
            raw_split=None,
            question=question,
            question_format="open",
            options=None,
            ground_truth=gt_list,
            ground_truth_text=gt_text,
            ground_truth_origin="wikidata+aliases",
            ck_text=counter_ev,
            ck_text_origin="llm_synth_model_specific",
            ck_target_answer=str(counter_answer).strip(),
            ck_target_matches_gt=ctr_is_gt,
            ck_relation=rel2,
            ck_relation_is_core=True,
            ck_relation_source="alias_match",
            ck_sub_type=None,
            hop_count=1,
            source_model=source_model,
            metadata={**common_meta, "ck_source_field": "counter_memory_aligned_evidence"},
        ))

    return rows


def build(source_model: str = "llama2-7b") -> Iterator[tuple[str, list[DatasetRow]]]:
    """Default: only the llama2-7b variant is used by the SABER benchmark."""
    yield f"conflictqa-popqa-{source_model}", _build_one(source_model)
